library(here)
library(Matrix)
library(igraph)
library(epicontacts)
library(visNetwork)
library(expm)
library(ggplot2)

source(here("code", "prep_functions.R"))
list2env(hospital(Wards = 5, RoomsPerWard = 10, BedsPerRoom = 2), envir = .GlobalEnv)
source(here("code", "parameters.R"))
source(here("code", "outbreak_simulation.R"))
source(here("code", "mcmc.R"))
source(here("code", "analysis_functions.R"))
source(here("code", "plot_functions.R"))
